#' YouTube Reporting API Objects 
#' Schedules reporting jobs containing your YouTube Analytics data and downloads the resulting bulk data reports in the form of CSV files.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2022-01-14 13:42:58
#' filename: /Users/jalvarado/apps//googleyoutubereportingv1.auto/R/youtubereporting_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' Empty Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); } The JSON representation for `Empty` is empty JSON object `{}`.
#' 
#' 
#' 
#' @return Empty object
#' 
#' @family Empty functions
#' @export
Empty <- function() {
    list()
}

#' GdataCompositeMedia Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param objectId gdata
#' @param referenceType gdata
#' @param path gdata
#' @param blobstore2Info gdata
#' @param sha1Hash gdata
#' @param md5Hash gdata
#' @param inline gdata
#' @param length gdata
#' @param crc32cHash gdata
#' @param cosmoBinaryReference gdata
#' @param blobRef gdata
#' 
#' @return GdataCompositeMedia object
#' 
#' @family GdataCompositeMedia functions
#' @export
GdataCompositeMedia <- function(objectId = NULL, referenceType = NULL, path = NULL,
    blobstore2Info = NULL, sha1Hash = NULL, md5Hash = NULL, inline = NULL, length = NULL,
    crc32cHash = NULL, cosmoBinaryReference = NULL, blobRef = NULL) {
    structure(list(objectId = objectId, referenceType = referenceType, path = path,
        blobstore2Info = blobstore2Info, sha1Hash = sha1Hash, md5Hash = md5Hash,
        inline = inline, length = length, crc32cHash = crc32cHash, cosmoBinaryReference = cosmoBinaryReference,
        blobRef = blobRef), class = c("gar_GdataCompositeMedia", "list"))
}

#' ReportType Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A report type.
#' 
#' @param deprecateTime The date/time when this report type was/will be deprecated
#' @param name The name of the report type (max
#' @param systemManaged True if this a system-managed report type; otherwise false
#' @param id The ID of the report type (max
#' 
#' @return ReportType object
#' 
#' @family ReportType functions
#' @export
ReportType <- function(deprecateTime = NULL, name = NULL, systemManaged = NULL, id = NULL) {
    structure(list(deprecateTime = deprecateTime, name = name, systemManaged = systemManaged,
        id = id), class = c("gar_ReportType", "list"))
}

#' Report Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A report's metadata including the URL from which the report itself can be downloaded.
#' 
#' @param createTime The date/time when this report was created
#' @param jobExpireTime The date/time when the job this report belongs to will expire/expired
#' @param startTime The start of the time period that the report instance covers
#' @param id The server-generated ID of the report
#' @param endTime The end of the time period that the report instance covers
#' @param jobId The ID of the job that created this report
#' @param downloadUrl The URL from which the report can be downloaded (max
#' 
#' @return Report object
#' 
#' @family Report functions
#' @export
Report <- function(createTime = NULL, jobExpireTime = NULL, startTime = NULL, id = NULL,
    endTime = NULL, jobId = NULL, downloadUrl = NULL) {
    structure(list(createTime = createTime, jobExpireTime = jobExpireTime, startTime = startTime,
        id = id, endTime = endTime, jobId = jobId, downloadUrl = downloadUrl), class = c("gar_Report",
        "list"))
}

#' GdataDownloadParameters Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param allowGzipCompression gdata
#' @param ignoreRange gdata
#' 
#' @return GdataDownloadParameters object
#' 
#' @family GdataDownloadParameters functions
#' @export
GdataDownloadParameters <- function(allowGzipCompression = NULL, ignoreRange = NULL) {
    structure(list(allowGzipCompression = allowGzipCompression, ignoreRange = ignoreRange),
        class = c("gar_GdataDownloadParameters", "list"))
}

#' ListReportTypesResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for ReportingService.ListReportTypes.
#' 
#' @param nextPageToken A token to retrieve next page of results
#' @param reportTypes The list of report types
#' 
#' @return ListReportTypesResponse object
#' 
#' @family ListReportTypesResponse functions
#' @export
ListReportTypesResponse <- function(nextPageToken = NULL, reportTypes = NULL) {
    structure(list(nextPageToken = nextPageToken, reportTypes = reportTypes), class = c("gar_ListReportTypesResponse",
        "list"))
}

#' GdataDiffVersionResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param objectSizeBytes gdata
#' @param objectVersion gdata
#' 
#' @return GdataDiffVersionResponse object
#' 
#' @family GdataDiffVersionResponse functions
#' @export
GdataDiffVersionResponse <- function(objectSizeBytes = NULL, objectVersion = NULL) {
    structure(list(objectSizeBytes = objectSizeBytes, objectVersion = objectVersion),
        class = c("gar_GdataDiffVersionResponse", "list"))
}

#' GdataDiffUploadRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param objectVersion gdata
#' @param objectInfo gdata
#' @param checksumsInfo gdata
#' 
#' @return GdataDiffUploadRequest object
#' 
#' @family GdataDiffUploadRequest functions
#' @export
GdataDiffUploadRequest <- function(objectVersion = NULL, objectInfo = NULL, checksumsInfo = NULL) {
    structure(list(objectVersion = objectVersion, objectInfo = objectInfo, checksumsInfo = checksumsInfo),
        class = c("gar_GdataDiffUploadRequest", "list"))
}

#' GdataMedia Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param cosmoBinaryReference gdata
#' @param diffUploadRequest gdata
#' @param md5Hash gdata
#' @param mediaId gdata
#' @param sha256Hash gdata
#' @param timestamp gdata
#' @param isPotentialRetry gdata
#' @param bigstoreObjectRef gdata
#' @param inline gdata
#' @param diffDownloadResponse gdata
#' @param contentTypeInfo gdata
#' @param length gdata
#' @param compositeMedia gdata
#' @param sha1Hash gdata
#' @param diffVersionResponse gdata
#' @param objectId gdata
#' @param token gdata
#' @param crc32cHash gdata
#' @param path gdata
#' @param filename gdata
#' @param hash gdata
#' @param referenceType gdata
#' @param hashVerified gdata
#' @param blobstore2Info gdata
#' @param downloadParameters gdata
#' @param algorithm gdata
#' @param contentType gdata
#' @param blobRef gdata
#' @param diffUploadResponse gdata
#' @param diffChecksumsResponse gdata
#' 
#' @return GdataMedia object
#' 
#' @family GdataMedia functions
#' @export
GdataMedia <- function(cosmoBinaryReference = NULL, diffUploadRequest = NULL, md5Hash = NULL,
    mediaId = NULL, sha256Hash = NULL, timestamp = NULL, isPotentialRetry = NULL,
    bigstoreObjectRef = NULL, inline = NULL, diffDownloadResponse = NULL, contentTypeInfo = NULL,
    length = NULL, compositeMedia = NULL, sha1Hash = NULL, diffVersionResponse = NULL,
    objectId = NULL, token = NULL, crc32cHash = NULL, path = NULL, filename = NULL,
    hash = NULL, referenceType = NULL, hashVerified = NULL, blobstore2Info = NULL,
    downloadParameters = NULL, algorithm = NULL, contentType = NULL, blobRef = NULL,
    diffUploadResponse = NULL, diffChecksumsResponse = NULL) {
    structure(list(cosmoBinaryReference = cosmoBinaryReference, diffUploadRequest = diffUploadRequest,
        md5Hash = md5Hash, mediaId = mediaId, sha256Hash = sha256Hash, timestamp = timestamp,
        isPotentialRetry = isPotentialRetry, bigstoreObjectRef = bigstoreObjectRef,
        inline = inline, diffDownloadResponse = diffDownloadResponse, contentTypeInfo = contentTypeInfo,
        length = length, compositeMedia = compositeMedia, sha1Hash = sha1Hash, diffVersionResponse = diffVersionResponse,
        objectId = objectId, token = token, crc32cHash = crc32cHash, path = path,
        filename = filename, hash = hash, referenceType = referenceType, hashVerified = hashVerified,
        blobstore2Info = blobstore2Info, downloadParameters = downloadParameters,
        algorithm = algorithm, contentType = contentType, blobRef = blobRef, diffUploadResponse = diffUploadResponse,
        diffChecksumsResponse = diffChecksumsResponse), class = c("gar_GdataMedia",
        "list"))
}

#' Job Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A job creating reports of a specific type.
#' 
#' @param systemManaged True if this a system-managed job that cannot be modified by the user; otherwise false
#' @param id The server-generated ID of the job (max
#' @param createTime The creation date/time of the job
#' @param reportTypeId The type of reports this job creates
#' @param expireTime The date/time when this job will expire/expired
#' @param name The name of the job (max
#' 
#' @return Job object
#' 
#' @family Job functions
#' @export
Job <- function(systemManaged = NULL, id = NULL, createTime = NULL, reportTypeId = NULL,
    expireTime = NULL, name = NULL) {
    structure(list(systemManaged = systemManaged, id = id, createTime = createTime,
        reportTypeId = reportTypeId, expireTime = expireTime, name = name), class = c("gar_Job",
        "list"))
}

#' GdataDiffDownloadResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param objectLocation gdata
#' 
#' @return GdataDiffDownloadResponse object
#' 
#' @family GdataDiffDownloadResponse functions
#' @export
GdataDiffDownloadResponse <- function(objectLocation = NULL) {
    structure(list(objectLocation = objectLocation), class = c("gar_GdataDiffDownloadResponse",
        "list"))
}

#' ListJobsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for ReportingService.ListJobs.
#' 
#' @param nextPageToken A token to retrieve next page of results
#' @param jobs The list of jobs
#' 
#' @return ListJobsResponse object
#' 
#' @family ListJobsResponse functions
#' @export
ListJobsResponse <- function(nextPageToken = NULL, jobs = NULL) {
    structure(list(nextPageToken = nextPageToken, jobs = jobs), class = c("gar_ListJobsResponse",
        "list"))
}

#' GdataObjectId Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param bucketName gdata
#' @param generation gdata
#' @param objectName gdata
#' 
#' @return GdataObjectId object
#' 
#' @family GdataObjectId functions
#' @export
GdataObjectId <- function(bucketName = NULL, generation = NULL, objectName = NULL) {
    structure(list(bucketName = bucketName, generation = generation, objectName = objectName),
        class = c("gar_GdataObjectId", "list"))
}

#' GdataContentTypeInfo Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param fromBytes gdata
#' @param bestGuess gdata
#' @param fromFileName gdata
#' @param fromHeader gdata
#' @param fromUrlPath gdata
#' 
#' @return GdataContentTypeInfo object
#' 
#' @family GdataContentTypeInfo functions
#' @export
GdataContentTypeInfo <- function(fromBytes = NULL, bestGuess = NULL, fromFileName = NULL,
    fromHeader = NULL, fromUrlPath = NULL) {
    structure(list(fromBytes = fromBytes, bestGuess = bestGuess, fromFileName = fromFileName,
        fromHeader = fromHeader, fromUrlPath = fromUrlPath), class = c("gar_GdataContentTypeInfo",
        "list"))
}

#' GdataDiffUploadResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param originalObject gdata
#' @param objectVersion gdata
#' 
#' @return GdataDiffUploadResponse object
#' 
#' @family GdataDiffUploadResponse functions
#' @export
GdataDiffUploadResponse <- function(originalObject = NULL, objectVersion = NULL) {
    structure(list(originalObject = originalObject, objectVersion = objectVersion),
        class = c("gar_GdataDiffUploadResponse", "list"))
}

#' GdataBlobstore2Info Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param readToken gdata
#' @param blobGeneration gdata
#' @param downloadReadHandle gdata
#' @param uploadMetadataContainer gdata
#' @param blobId gdata
#' 
#' @return GdataBlobstore2Info object
#' 
#' @family GdataBlobstore2Info functions
#' @export
GdataBlobstore2Info <- function(readToken = NULL, blobGeneration = NULL, downloadReadHandle = NULL,
    uploadMetadataContainer = NULL, blobId = NULL) {
    structure(list(readToken = readToken, blobGeneration = blobGeneration, downloadReadHandle = downloadReadHandle,
        uploadMetadataContainer = uploadMetadataContainer, blobId = blobId), class = c("gar_GdataBlobstore2Info",
        "list"))
}

#' GdataDiffChecksumsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' gdata
#' 
#' @param objectSizeBytes gdata
#' @param checksumsLocation gdata
#' @param objectVersion gdata
#' @param objectLocation gdata
#' @param chunkSizeBytes gdata
#' 
#' @return GdataDiffChecksumsResponse object
#' 
#' @family GdataDiffChecksumsResponse functions
#' @export
GdataDiffChecksumsResponse <- function(objectSizeBytes = NULL, checksumsLocation = NULL,
    objectVersion = NULL, objectLocation = NULL, chunkSizeBytes = NULL) {
    structure(list(objectSizeBytes = objectSizeBytes, checksumsLocation = checksumsLocation,
        objectVersion = objectVersion, objectLocation = objectLocation, chunkSizeBytes = chunkSizeBytes),
        class = c("gar_GdataDiffChecksumsResponse", "list"))
}


#' ListReportsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for ReportingService.ListReports.
#' 
#' @param nextPageToken A token to retrieve next page of results
#' @param reports The list of report types
#' 
#' @return ListReportsResponse object
#' 
#' @family ListReportsResponse functions
#' @export


ListReportsResponse <- function(nextPageToken = NULL, reports = NULL) {



    structure(list(nextPageToken = nextPageToken, reports = reports), class = c("gar_ListReportsResponse",
        "list"))
}

