#' YouTube Analytics API Objects 
#' Retrieves your YouTube Analytics data.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2022-01-07 12:06:31
#' filename: /Users/jalvarado/apps/cdc/metrics/r_packages//googleyoutubeAnalyticsv2.auto/R/youtubeAnalytics_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' ResultTableColumnHeader Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The description of a column of the result table.
#' 
#' @param dataType The type of the data in the column (`STRING`, `INTEGER`, `FLOAT`, etc
#' @param name The name of the dimension or metric
#' @param columnType The type of the column (`DIMENSION` or `METRIC`)
#' 
#' @return ResultTableColumnHeader object
#' 
#' @family ResultTableColumnHeader functions
#' @export
ResultTableColumnHeader <- function(dataType = NULL, name = NULL, columnType = NULL) {
    structure(list(dataType = dataType, name = name, columnType = columnType), class = c("gar_ResultTableColumnHeader",
        "list"))
}

#' Errors Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Request Error information. The presence of an error field signals that the operation has failed.
#' 
#' @param requestId Request identifier generated by the service, which can be used to identify the error in the logs
#' @param error Specific error description and codes
#' @param code Global error code
#' 
#' @return Errors object
#' 
#' @family Errors functions
#' @export
Errors <- function(requestId = NULL, error = NULL, code = NULL) {
    structure(list(requestId = requestId, error = error, code = code), class = c("gar_Errors",
        "list"))
}

#' GroupItemResource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param id The channel, video, playlist, or asset ID that YouTube uses to uniquely identify the item that is being added to the group
#' 
#' @return GroupItemResource object
#' 
#' @family GroupItemResource functions
#' @export
GroupItemResource <- function(id = NULL) {
    structure(list(kind = kind, id = id), class = c("gar_GroupItemResource", "list"))
}

#' ListGroupItemsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for GroupsService.ListGroupItems.
#' 
#' @param items A list of groups that match the API request parameters
#' @param errors Apiary error details
#' @param etag The Etag of this resource
#' 
#' @return ListGroupItemsResponse object
#' 
#' @family ListGroupItemsResponse functions
#' @export
ListGroupItemsResponse <- function(items = NULL, errors = NULL, etag = NULL) {
    structure(list(kind = kind, items = items, errors = errors, etag = etag), class = c("gar_ListGroupItemsResponse",
        "list"))
}

#' ErrorProto Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Describes one specific error.
#' 
#' @param location Location of the error, as specified by the location type
#' @param domain Error domain
#' @param externalErrorMessage A short explanation for the error, which can be shared outside Google
#' @param argument Error arguments, to be used when building user-friendly error messages given the error domain and code
#' @param code Error code in the error domain
#' @param locationType No description
#' @param debugInfo Debugging information, which should not be shared externally
#' 
#' @return ErrorProto object
#' 
#' @family ErrorProto functions
#' @export
ErrorProto <- function(location = NULL, domain = NULL, externalErrorMessage = NULL,
    argument = NULL, code = NULL, locationType = NULL, debugInfo = NULL) {
    structure(list(location = location, domain = domain, externalErrorMessage = externalErrorMessage,
        argument = argument, code = code, locationType = locationType, debugInfo = debugInfo),
        class = c("gar_ErrorProto", "list"))
}

#' GroupItem Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A group item.
#' 
#' @param resource The `resource` object contains information that identifies the item being added to the group
#' @param groupId The ID that YouTube uses to uniquely identify the group that contains the item
#' @param errors Apiary error details
#' @param etag The Etag of this resource
#' @param id The ID that YouTube uses to uniquely identify the `channel`, `video`, `playlist`, or `asset` resource that is included in the group
#' 
#' @return GroupItem object
#' 
#' @family GroupItem functions
#' @export
GroupItem <- function(resource = NULL, groupId = NULL, errors = NULL, etag = NULL,
    id = NULL) {
    structure(list(resource = resource, groupId = groupId, kind = kind, errors = errors,
        etag = etag, id = id), class = c("gar_GroupItem", "list"))
}

#' GroupContentDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A group's content details.
#' 
#' @param itemCount The number of items in the group
#' @param itemType The type of resources that the group contains
#' 
#' @return GroupContentDetails object
#' 
#' @family GroupContentDetails functions
#' @export
GroupContentDetails <- function(itemCount = NULL, itemType = NULL) {
    structure(list(itemCount = itemCount, itemType = itemType), class = c("gar_GroupContentDetails",
        "list"))
}

#' GroupSnippet Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A group snippet.
#' 
#' @param title The group name
#' @param publishedAt The date and time that the group was created
#' 
#' @return GroupSnippet object
#' 
#' @family GroupSnippet functions
#' @export
GroupSnippet <- function(title = NULL, publishedAt = NULL) {
    structure(list(title = title, publishedAt = publishedAt), class = c("gar_GroupSnippet",
        "list"))
}

#' Group Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A group.
#' 
#' @param etag The Etag of this resource
#' @param snippet The `snippet` object contains basic information about the group, including its creation date and name
#' @param id The ID that YouTube uses to uniquely identify the group
#' @param errors Apiary error details
#' @param contentDetails The `contentDetails` object contains additional information about the group, such as the number and type of items that it contains
#' 
#' @return Group object
#' 
#' @family Group functions
#' @export
Group <- function(etag = NULL, snippet = NULL, id = NULL, errors = NULL, contentDetails = NULL) {
    structure(list(etag = etag, snippet = snippet, id = id, errors = errors, contentDetails = contentDetails,
        kind = kind), class = c("gar_Group", "list"))
}

#' QueryResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for TargetedQueriesService.Query.
#' 
#' @param columnHeaders This value specifies information about the data returned in the `rows` fields
#' @param rows The list contains all rows of the result table
#' @param errors When set, indicates that the operation failed
#' 
#' @return QueryResponse object
#' 
#' @family QueryResponse functions
#' @export
QueryResponse <- function(columnHeaders = NULL, rows = NULL, errors = NULL) {
    structure(list(kind = kind, columnHeaders = columnHeaders, rows = rows, errors = errors),
        class = c("gar_QueryResponse", "list"))
}

#' ListGroupsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Response message for GroupsService.ListGroups.
#' 
#' @param nextPageToken The token that can be used as the value of the `pageToken` parameter to retrieve the next page in the result set
#' @param errors Apiary error details
#' @param items A list of groups that match the API request parameters
#' @param etag The Etag of this resource
#' 
#' @return ListGroupsResponse object
#' 
#' @family ListGroupsResponse functions
#' @export
ListGroupsResponse <- function(nextPageToken = NULL, errors = NULL, items = NULL,
    etag = NULL) {
    structure(list(kind = kind, nextPageToken = nextPageToken, errors = errors, items = items,
        etag = etag), class = c("gar_ListGroupsResponse", "list"))
}


#' EmptyResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Empty response.
#' 
#' @param errors Apiary error details
#' 
#' @return EmptyResponse object
#' 
#' @family EmptyResponse functions
#' @export


EmptyResponse <- function(errors = NULL) {



    structure(list(errors = errors), class = c("gar_EmptyResponse", "list"))
}

