#' YouTube Analytics API
#' Retrieves your YouTube Analytics data.
#'
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2022-01-07 12:06:30
#' filename: /Users/jalvarado/apps/cdc/metrics/r_packages//googleyoutubeAnalyticsv2.auto/R/youtubeAnalytics_functions.R
#' api_json: api_json
#'
#' @details
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' }
#'
#' @docType package
#' @name youtubeAnalytics_googleAuthR
#'
NULL
## NULL

#' Retrieve your YouTube Analytics reports.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param metrics A comma-separated list of YouTube Analytics metrics, such as `views` or `likes,dislikes`
#' @param filters A list of filters that should be applied when retrieving YouTube Analytics data
#' @param includeHistoricalChannelData If set to true historical data (i
#' @param currency The currency to which financial metrics should be converted
#' @param ids Identifies the YouTube channel or content owner for which you are retrieving YouTube Analytics data
#' @param endDate The end date for fetching YouTube Analytics data
#' @param startDate The start date for fetching YouTube Analytics data
#' @param dimensions A comma-separated list of YouTube Analytics dimensions, such as `views` or `ageGroup,gender`
#' @param startIndex An index of the first entity to retrieve
#' @param sort A comma-separated list of dimensions or metrics that determine the sort order for YouTube Analytics data
#' @param maxResults The maximum number of rows to include in the response
#' @importFrom googleAuthR gar_api_generator
#' @export
reports.query <- function(metrics = NULL, filters = NULL, includeHistoricalChannelData = NULL,
    currency = NULL, ids = NULL, endDate = NULL, startDate = NULL, dimensions = NULL,
    startIndex = NULL, sort = NULL, maxResults = NULL) {
    url <- "https://youtubeanalytics.googleapis.com/v2/reports"
    # youtubeAnalytics.reports.query
    pars = list(metrics = metrics, filters = filters, includeHistoricalChannelData = includeHistoricalChannelData,
        currency = currency, ids = ids, endDate = endDate, startDate = startDate,
        dimensions = dimensions, startIndex = startIndex, sort = sort, maxResults = maxResults)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Removes an item from a group.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param onBehalfOfContentOwner This parameter can only be used in a properly authorized request
#' @param id The `id` parameter specifies the YouTube group item ID of the group item that is being deleted
#' @importFrom googleAuthR gar_api_generator
#' @export
groupItems.delete <- function(onBehalfOfContentOwner = NULL, id = NULL) {
    url <- "https://youtubeanalytics.googleapis.com/v2/groupItems"
    # youtubeAnalytics.groupItems.delete
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner, id = id)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Returns a collection of group items that match the API request parameters.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param groupId The `groupId` parameter specifies the unique ID of the group for which you want to retrieve group items
#' @param onBehalfOfContentOwner This parameter can only be used in a properly authorized request
#' @importFrom googleAuthR gar_api_generator
#' @export
groupItems.list <- function(groupId = NULL, onBehalfOfContentOwner = NULL) {
    url <- "https://youtubeanalytics.googleapis.com/v2/groupItems"
    # youtubeAnalytics.groupItems.list
    pars = list(groupId = groupId, onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Creates a group item.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param GroupItem The \link{GroupItem} object to pass to this method
#' @param onBehalfOfContentOwner This parameter can only be used in a properly authorized request
#' @importFrom googleAuthR gar_api_generator
#' @family GroupItem functions
#' @export
groupItems.insert <- function(GroupItem, onBehalfOfContentOwner = NULL) {
    url <- "https://youtubeanalytics.googleapis.com/v2/groupItems"
    # youtubeAnalytics.groupItems.insert
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GroupItem, "gar_GroupItem"))

    f(the_body = GroupItem)

}

#' Deletes a group.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param id The `id` parameter specifies the YouTube group ID of the group that is being deleted
#' @param onBehalfOfContentOwner This parameter can only be used in a properly authorized request
#' @importFrom googleAuthR gar_api_generator
#' @export
groups.delete <- function(id = NULL, onBehalfOfContentOwner = NULL) {
    url <- "https://youtubeanalytics.googleapis.com/v2/groups"
    # youtubeAnalytics.groups.delete
    pars = list(id = id, onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Modifies a group. For example, you could change a group's title.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Group The \link{Group} object to pass to this method
#' @param onBehalfOfContentOwner This parameter can only be used in a properly authorized request
#' @importFrom googleAuthR gar_api_generator
#' @family Group functions
#' @export
groups.update <- function(Group, onBehalfOfContentOwner = NULL) {
    url <- "https://youtubeanalytics.googleapis.com/v2/groups"
    # youtubeAnalytics.groups.update
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "PUT", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(Group, "gar_Group"))

    f(the_body = Group)

}

#' Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param id The `id` parameter specifies a comma-separated list of the YouTube group ID(s) for the resource(s) that are being retrieved
#' @param mine This parameter can only be used in a properly authorized request
#' @param pageToken The `pageToken` parameter identifies a specific page in the result set that should be returned
#' @param onBehalfOfContentOwner This parameter can only be used in a properly authorized request
#' @importFrom googleAuthR gar_api_generator
#' @export
groups.list <- function(id = NULL, mine = NULL, pageToken = NULL, onBehalfOfContentOwner = NULL) {
    url <- "https://youtubeanalytics.googleapis.com/v2/groups"
    # youtubeAnalytics.groups.list
    pars = list(id = id, mine = mine, pageToken = pageToken, onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}


#' Creates a group.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/analytics}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/youtube
#' \item https://www.googleapis.com/auth/youtube.readonly
#' \item https://www.googleapis.com/auth/youtubepartner
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/youtube.readonly, https://www.googleapis.com/auth/youtubepartner, https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Group The \link{Group} object to pass to this method
#' @param onBehalfOfContentOwner This parameter can only be used in a properly authorized request
#' @importFrom googleAuthR gar_api_generator
#' @family Group functions
#' @export


groups.insert <- function(Group, onBehalfOfContentOwner = NULL) {


    url <- "https://youtubeanalytics.googleapis.com/v2/groups"
    # youtubeAnalytics.groups.insert
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner)

    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)

    stopifnot(inherits(Group, "gar_Group"))

    f(the_body = Group)


}



