#' YouTube Reporting API
#' Schedules reporting jobs containing your YouTube Analytics data and downloads the resulting bulk data reports in the form of CSV files.
#'
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2022-01-14 13:42:58
#' filename: /Users/jalvarado/apps//googleyoutubereportingv1.auto/R/youtubereporting_functions.R
#' api_json: api_json
#'
#' @details
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics.readonly
#' \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' }
#'
#' @docType package
#' @name youtubereporting_googleAuthR
#'
NULL
## NULL

#' Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param resourceName Name of the media that is being downloaded
#' @importFrom googleAuthR gar_api_generator
#' @export
media.download <- function(resourceName) {
    url <- sprintf("https://youtubereporting.googleapis.com/v1/media/{+resourceName}",
        resourceName)
    # youtubereporting.media.download
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Lists report types.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param pageSize Requested page size
#' @param includeSystemManaged If set to true, also system-managed report types will be returned; otherwise only the report types that can be used to create new reporting jobs will be returned
#' @param onBehalfOfContentOwner The content owner's external ID on which behalf the user is acting on
#' @param pageToken A token identifying a page of results the server should return
#' @importFrom googleAuthR gar_api_generator
#' @export
reportTypes.list <- function(pageSize = NULL, includeSystemManaged = NULL, onBehalfOfContentOwner = NULL,
    pageToken = NULL) {
    url <- "https://youtubereporting.googleapis.com/v1/reportTypes"
    # youtubereporting.reportTypes.list
    pars = list(pageSize = pageSize, includeSystemManaged = includeSystemManaged,
        onBehalfOfContentOwner = onBehalfOfContentOwner, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Deletes a job.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param jobId The ID of the job to delete
#' @param onBehalfOfContentOwner The content owner's external ID on which behalf the user is acting on
#' @importFrom googleAuthR gar_api_generator
#' @export
jobs.delete <- function(jobId, onBehalfOfContentOwner = NULL) {
    url <- sprintf("https://youtubereporting.googleapis.com/v1/jobs/%s", jobId)
    # youtubereporting.jobs.delete
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "DELETE", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Gets a job.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param jobId The ID of the job to retrieve
#' @param onBehalfOfContentOwner The content owner's external ID on which behalf the user is acting on
#' @importFrom googleAuthR gar_api_generator
#' @export
jobs.get <- function(jobId, onBehalfOfContentOwner = NULL) {
    url <- sprintf("https://youtubereporting.googleapis.com/v1/jobs/%s", jobId)
    # youtubereporting.jobs.get
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Creates a job and returns it.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Job The \link{Job} object to pass to this method
#' @param onBehalfOfContentOwner The content owner's external ID on which behalf the user is acting on
#' @importFrom googleAuthR gar_api_generator
#' @family Job functions
#' @export
jobs.create <- function(Job, onBehalfOfContentOwner = NULL) {
    url <- "https://youtubereporting.googleapis.com/v1/jobs"
    # youtubereporting.jobs.create
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(Job, "gar_Job"))

    f(the_body = Job)

}

#' Lists jobs.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param includeSystemManaged If set to true, also system-managed jobs will be returned; otherwise only user-created jobs will be returned
#' @param pageSize Requested page size
#' @param onBehalfOfContentOwner The content owner's external ID on which behalf the user is acting on
#' @param pageToken A token identifying a page of results the server should return
#' @importFrom googleAuthR gar_api_generator
#' @export
jobs.list <- function(includeSystemManaged = NULL, pageSize = NULL, onBehalfOfContentOwner = NULL,
    pageToken = NULL) {
    url <- "https://youtubereporting.googleapis.com/v1/jobs"
    # youtubereporting.jobs.list
    pars = list(includeSystemManaged = includeSystemManaged, pageSize = pageSize,
        onBehalfOfContentOwner = onBehalfOfContentOwner, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Lists reports created by a specific job. Returns NOT_FOUND if the job does not exist.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param jobId The ID of the job
#' @param createdAfter If set, only reports created after the specified date/time are returned
#' @param startTimeAtOrAfter If set, only reports whose start time is greater than or equal the specified date/time are returned
#' @param pageSize Requested page size
#' @param startTimeBefore If set, only reports whose start time is smaller than the specified date/time are returned
#' @param onBehalfOfContentOwner The content owner's external ID on which behalf the user is acting on
#' @param pageToken A token identifying a page of results the server should return
#' @importFrom googleAuthR gar_api_generator
#' @export
jobs.reports.list <- function(jobId, createdAfter = NULL, startTimeAtOrAfter = NULL,
    pageSize = NULL, startTimeBefore = NULL, onBehalfOfContentOwner = NULL, pageToken = NULL) {
    url <- sprintf("https://youtubereporting.googleapis.com/v1/jobs/%s/reports",
        jobId)
    # youtubereporting.jobs.reports.list
    pars = list(createdAfter = createdAfter, startTimeAtOrAfter = startTimeAtOrAfter,
        pageSize = pageSize, startTimeBefore = startTimeBefore, onBehalfOfContentOwner = onBehalfOfContentOwner,
        pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}


#' Gets the metadata of a specific report.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/youtube/reporting/v1/reports/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/yt-analytics-monetary.readonly
#' \item https://www.googleapis.com/auth/yt-analytics.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/yt-analytics-monetary.readonly, https://www.googleapis.com/auth/yt-analytics.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param jobId The ID of the job

#' @param reportId The ID of the report to retrieve

#' @param onBehalfOfContentOwner The content owner's external ID on which behalf the user is acting on
#' @importFrom googleAuthR gar_api_generator
#' @export


jobs.reports.get <- function(jobId, reportId, onBehalfOfContentOwner = NULL) {


    url <- sprintf("https://youtubereporting.googleapis.com/v1/jobs/%s/reports/%s",
        jobId, reportId)
    # youtubereporting.jobs.reports.get
    pars = list(onBehalfOfContentOwner = onBehalfOfContentOwner)

    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)

    f()


}



